name: Docker Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Reposu klonla
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bağımlılıkları kur
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Testleri çalıştır
        run: pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image oluştur ve gönder
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      - name: Çalışan konteynerları durdur (eğer varsa)
        run: |
          docker stop gracious_lalande random-app || true
          docker rm gracious_lalande random-app || true

      - name: Yeni konteynerları başlat
        run: |
          docker run -d -p 5000:5000 --name random-app ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          docker run -d -p 5001:5000 --name gracious_lalande ozturk25/flask-random-app:1.0